# Generated by Django 3.1.7 on 2021-09-05 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20210905_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replie',
            name='owner',
        ),
    ]
