# Generated by Django 3.1.7 on 2021-09-11 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff_members', '0001_initial'),
        ('students', '0003_remove_replie_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='visiting_to',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='staff_members.staffprofile'),
        ),
        migrations.AlterField(
            model_name='comlaint',
            name='status',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.DeleteModel(
            name='Replie',
        ),
        migrations.DeleteModel(
            name='StaffProfile',
        ),
        migrations.DeleteModel(
            name='Visitor',
        ),
    ]
