# Generated by Django 3.1.7 on 2021-09-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20210911_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='mobilenum',
            field=models.BigIntegerField(),
        ),
    ]
