# Generated by Django 3.1.7 on 2021-09-14 12:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20210914_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='comlaint',
            name='title',
            field=models.CharField(default=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True), max_length=100),
        ),
    ]
