# Generated by Django 3.1.7 on 2021-09-14 12:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_comlaint_title'),
        ('staff_members', '0002_auto_20210914_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='staff_members.staffprofile')),
                ('replying_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.comlaint')),
            ],
        ),
    ]
