# Generated by Django 3.1.7 on 2021-12-01 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_members', '0003_replie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Replie',
        ),
    ]
