# Generated by Django 3.1.7 on 2021-09-11 06:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0004_auto_20210911_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('mobile_num', models.IntegerField()),
                ('in_time', models.TimeField(auto_now_add=True)),
                ('out_time', models.TimeField(null=True)),
                ('visiting_to', models.ManyToManyField(to='students.StudentProfile')),
            ],
        ),
    ]
