# Generated by Django 3.1.7 on 2021-09-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visitors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='visitor',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
