# Generated by Django 3.1.7 on 2021-12-06 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Visitors', '0003_auto_20210914_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='last_name',
        ),
    ]
