# Generated by Django 3.1.7 on 2021-12-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visitors', '0004_auto_20211206_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='out_time',
        ),
        migrations.AddField(
            model_name='visitor',
            name='purpose_of_visiting',
            field=models.TextField(default='Not metioned'),
        ),
    ]
