# Generated by Django 3.1.7 on 2021-12-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visitors', '0005_auto_20211206_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='number_of_visitors',
            field=models.IntegerField(default=1),
        ),
    ]
