# Generated by Django 3.1.7 on 2021-12-06 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20211201_1038'),
        ('Visitors', '0006_visitor_number_of_visitors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='visiting_to',
        ),
        migrations.AddField(
            model_name='visitor',
            name='visiting_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.studentprofile'),
        ),
    ]
